- name: Build and push docker image to docker hub
  hosts: localhost
  tasks:
    - name: stop container
      command: sudo docker stop tomcat-dockerfile-container

    - name: Run Docker file to build docker image
      command: sudo docker build -t kumard99/tomcat-dockerfile .

    - name: Build Docker container
      command: sudo docker run -d --name tomcat-dockerfile-container -p 8085:8080 kumard99/tomcat-dockerfile

    - name: Push Image to Docker hub(We can Save docker login credentials in jenkins config)
      command: sudo docker push kumard99/tomcat-dockerfile
